name: Test ts errors on
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: write  # for eps1lon/actions-label-merge-conflict to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: test ts
        working-directory: ./bigbluebutton-html5
        run: sh -c '
          npm ci
          npm install typescript
          npx tsc
        '




