name: Test ts errors on
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: write  # for eps1lon/actions-label-merge-conflict to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1




